shallow_clone: true

image:
    - Visual Studio 2019

environment:
   matrix:
      - generator: "Visual Studio 17 2022"

platform:
   - x64

configuration:
   - Debug
   - Release

init:
   - cmd: cmake --version
   - cmd: msbuild /version

before_build:
   - cmake --version
   - cmake -A %platform% -G "%generator%" .

build_script:
   - mkdir ZenUnitAndMetalMock
   - appveyor DownloadFile https://raw.githubusercontent.com/NeilJustice/ZenUnitAndMetalMock/main/ZenUnitAndMetalMock/ZenUnit.h -FileName ZenUnitAndMetalMock/ZenUnit.h
   - appveyor DownloadFile https://raw.githubusercontent.com/NeilJustice/ZenUnitAndMetalMock/main/ZenUnitAndMetalMock/MetalMock.h -FileName ZenUnitAndMetalMock/MetalMock.h
   - cmake --build . --config %configuration% -- /m
