#!/bin/bash
set -u

osname="$(uname --operating-system)"
if [[ "$osname" == *"Linux" ]]; then
   JenkinsJobs/LinuxCloudundancyDebugClangSanitizers.sh
elif [ "$osname" == "Msys" ]; then
   powershell JenkinsJobs/WindowsCloudundancyDebug.ps1
fi
jenkinsJobExitCode=$?
if [ "$jenkinsJobExitCode" -ne 0 ]; then
   echo "pre-commit: Jenkins job failed with exit code $jenkinsJobExitCode. Disallowing commit."
   exit 1
fi
echo "pre-commit: Jenkins job succeeded. Allowing commit."
