#!/bin/bash
set -eu

osname="$(uname --operating-system)"
if [[ "$osname" == *"Linux" ]]; then
   ./JenkinsJobs/Linux/Cloudundancy-Cppcheck.sh
   ./JenkinsJobs/Linux/CloudundancyDevOpsPython-Mypy-Flake8-Pylint.sh
   ./JenkinsJobs/Linux/Cloudundancy-Debug-Clang.sh
elif [ "$osname" == "Msys" ]; then
   pwsh.exe JenkinsJobs/Windows/Cloudundancy-Cppcheck.ps1
   pwsh.exe JenkinsJobs/Windows/CloudundancyDevOpsPython-Mypy-Flake8-Pylint.ps1
   pwsh.exe JenkinsJobs/Windows/Cloudundancy-Debug.ps1 "OFF"
fi
jenkinsJobExitCode=$?
if [ "$jenkinsJobExitCode" -ne 0 ]; then
   echo "<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>"
   echo "pre-commit: Jenkins job failed with exit code $jenkinsJobExitCode. Disallowing commit."
   echo "<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>"
   exit 1
fi
echo "***************************************************"
echo "pre-commit: Jenkins job succeeded. Allowing commit."
echo "***************************************************"
