name: Cloudundancy
on: push

jobs:
  build:
    runs-on: windows-2025-vs2026
    strategy:
      matrix:
         cmake_build_type: [Debug, RelWithDebInfo]
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v8
        with:
          name: WindowsCPlusPlusBuilder
          github-token: ${{ secrets.WINDOWSCPLUSPLUSBUILDER_READ_PAT }}
          repository: NeilJustice/WindowsCPlusPlusBuilder
          run-id: 33347859387
          path: WindowsCPlusPlusBuilder/

      - name: Download ZenUnit.h and MetalMock.h
        run: |
           curl https://raw.githubusercontent.com/NeilJustice/ZenUnitAndMetalMock/main/ZenUnitAndMetalMock/ZenUnit.h --create-dirs -o "$GITHUB_WORKSPACE/ZenUnitAndMetalMock/ZenUnit.h"
           curl https://raw.githubusercontent.com/NeilJustice/ZenUnitAndMetalMock/main/ZenUnitAndMetalMock/MetalMock.h --create-dirs -o "$GITHUB_WORKSPACE/ZenUnitAndMetalMock/MetalMock.h"
           
      - uses: ilammy/msvc-dev-cmd@v1 # Places MSBuild.exe on the PATH, which is invoked by WindowsCPlusPlusBuilder.exe
      
      - name: Run WindowsCPlusPlusBuilder
        run: |
           WindowsCPlusPlusBuilder/WindowsCPlusPlusBuilder.exe build-cpp-solution `
              --solution-name=Cloudundancy `
              --configuration="${{ matrix.cmake_build_type }}" `
              --cmake-definitions="" `
              --install=false
